// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKmKjiVZnrNqb6keTwznkDZrtrNhqpq0Q',
    appId: '1:545350734407:web:87ae7cac751640e61ed762',
    messagingSenderId: '545350734407',
    projectId: 'myskoda-bc7c0',
    authDomain: 'myskoda-bc7c0.firebaseapp.com',
    storageBucket: 'myskoda-bc7c0.appspot.com',
    measurementId: 'G-NX20L8FBXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJJk5liCb1vsj_V1eqA-EU5wH6R5eqgUw',
    appId: '1:545350734407:android:c283093649e5c0c71ed762',
    messagingSenderId: '545350734407',
    projectId: 'myskoda-bc7c0',
    storageBucket: 'myskoda-bc7c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHfo3K35U-p_MyLotpzFmgrpZHWwKj7aQ',
    appId: '1:545350734407:ios:6f13f247bbfd33f81ed762',
    messagingSenderId: '545350734407',
    projectId: 'myskoda-bc7c0',
    storageBucket: 'myskoda-bc7c0.appspot.com',
    iosClientId: '545350734407-c4ej1i37o1j26hn8vrodlaquk60f8isq.apps.googleusercontent.com',
    iosBundleId: 'com.example.skodaConnect',
  );
}
